name: CI (Vite React)

on:
  pull_request:
  push:
    branches: 
       - dev

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout index
        run: test -f index.html
